### ISSUE TITLE
Malformed wav files

### ISSUE THREAD

**Issue by strob** [lowerquality/drift#1]
Something in 813b2e3a259e035eb2ae68fa250d08d636fda5ec caused a regression on the seeking control. While click-to-seek works in Firefox, it's broken in Chrome and Safari.

It seems to be our familiar problem with the wav files. From
```sh
ffmpeg -i audio.wav
```
we see:
```
[wav @ 0x7fd10d001400] Ignoring maximum wav data size, file may be invalid
```

You need to give ffmpeg a file object on disk it can write to so it can set the headers correctly.

**Comment by maxhawkins** [comment]
Yes, it's the same issue as before. Im aware of it. I'll fix it later by
manually rewriting the length after reading from ffmpeg.
